import Foundation

extension Surah {
    // 114 surahs
    static let all: [Surah] = [
        Surah(id: 1, nameArabic: "الفاتحة", nameSimple: "Al-Fatihah", nameTranslation: "The Opener", versesCount: 7, revelationPlace: "makkah"),
        Surah(id: 2, nameArabic: "البقرة", nameSimple: "Al-Baqarah", nameTranslation: "The Cow", versesCount: 286, revelationPlace: "madinah"),
        Surah(id: 3, nameArabic: "آل عمران", nameSimple: "Ali 'Imran", nameTranslation: "Family of Imran", versesCount: 200, revelationPlace: "madinah"),
        Surah(id: 4, nameArabic: "النساء", nameSimple: "An-Nisa", nameTranslation: "The Women", versesCount: 176, revelationPlace: "madinah"),
        Surah(id: 5, nameArabic: "المائدة", nameSimple: "Al-Ma'idah", nameTranslation: "The Table Spread", versesCount: 120, revelationPlace: "madinah"),
        Surah(id: 6, nameArabic: "الأنعام", nameSimple: "Al-An'am", nameTranslation: "The Cattle", versesCount: 165, revelationPlace: "makkah"),
        Surah(id: 7, nameArabic: "الأعراف", nameSimple: "Al-A'raf", nameTranslation: "The Heights", versesCount: 206, revelationPlace: "makkah"),
        Surah(id: 8, nameArabic: "الأنفال", nameSimple: "Al-Anfal", nameTranslation: "The Spoils of War", versesCount: 75, revelationPlace: "madinah"),
        Surah(id: 9, nameArabic: "التوبة", nameSimple: "At-Tawbah", nameTranslation: "The Repentance", versesCount: 129, revelationPlace: "madinah"),
        Surah(id: 10, nameArabic: "يونس", nameSimple: "Yunus", nameTranslation: "Jonah", versesCount: 109, revelationPlace: "makkah"),
        Surah(id: 11, nameArabic: "هود", nameSimple: "Hud", nameTranslation: "Hud", versesCount: 123, revelationPlace: "makkah"),
        Surah(id: 12, nameArabic: "يوسف", nameSimple: "Yusuf", nameTranslation: "Joseph", versesCount: 111, revelationPlace: "makkah"),
        Surah(id: 13, nameArabic: "الرعد", nameSimple: "Ar-Ra'd", nameTranslation: "The Thunder", versesCount: 43, revelationPlace: "madinah"),
        Surah(id: 14, nameArabic: "ابراهيم", nameSimple: "Ibrahim", nameTranslation: "Abraham", versesCount: 52, revelationPlace: "makkah"),
        Surah(id: 15, nameArabic: "الحجر", nameSimple: "Al-Hijr", nameTranslation: "The Rocky Tract", versesCount: 99, revelationPlace: "makkah"),
        Surah(id: 16, nameArabic: "النحل", nameSimple: "An-Nahl", nameTranslation: "The Bee", versesCount: 128, revelationPlace: "makkah"),
        Surah(id: 17, nameArabic: "الإسراء", nameSimple: "Al-Isra", nameTranslation: "The Night Journey", versesCount: 111, revelationPlace: "makkah"),
        Surah(id: 18, nameArabic: "الكهف", nameSimple: "Al-Kahf", nameTranslation: "The Cave", versesCount: 110, revelationPlace: "makkah"),
        Surah(id: 19, nameArabic: "مريم", nameSimple: "Maryam", nameTranslation: "Mary", versesCount: 98, revelationPlace: "makkah"),
        Surah(id: 20, nameArabic: "طه", nameSimple: "Taha", nameTranslation: "Ta-Ha", versesCount: 135, revelationPlace: "makkah"),
        Surah(id: 21, nameArabic: "الأنبياء", nameSimple: "Al-Anbya", nameTranslation: "The Prophets", versesCount: 112, revelationPlace: "makkah"),
        Surah(id: 22, nameArabic: "الحج", nameSimple: "Al-Hajj", nameTranslation: "The Pilgrimage", versesCount: 78, revelationPlace: "madinah"),
        Surah(id: 23, nameArabic: "المؤمنون", nameSimple: "Al-Mu'minun", nameTranslation: "The Believers", versesCount: 118, revelationPlace: "makkah"),
        Surah(id: 24, nameArabic: "النور", nameSimple: "An-Nur", nameTranslation: "The Light", versesCount: 64, revelationPlace: "madinah"),
        Surah(id: 25, nameArabic: "الفرقان", nameSimple: "Al-Furqan", nameTranslation: "The Criterion", versesCount: 77, revelationPlace: "makkah"),
        Surah(id: 26, nameArabic: "الشعراء", nameSimple: "Ash-Shu'ara", nameTranslation: "The Poets", versesCount: 227, revelationPlace: "makkah"),
        Surah(id: 27, nameArabic: "النمل", nameSimple: "An-Naml", nameTranslation: "The Ant", versesCount: 93, revelationPlace: "makkah"),
        Surah(id: 28, nameArabic: "القصص", nameSimple: "Al-Qasas", nameTranslation: "The Stories", versesCount: 88, revelationPlace: "makkah"),
        Surah(id: 29, nameArabic: "العنكبوت", nameSimple: "Al-'Ankabut", nameTranslation: "The Spider", versesCount: 69, revelationPlace: "makkah"),
        Surah(id: 30, nameArabic: "الروم", nameSimple: "Ar-Rum", nameTranslation: "The Romans", versesCount: 60, revelationPlace: "makkah"),
        Surah(id: 31, nameArabic: "لقمان", nameSimple: "Luqman", nameTranslation: "Luqman", versesCount: 34, revelationPlace: "makkah"),
        Surah(id: 32, nameArabic: "السجدة", nameSimple: "As-Sajdah", nameTranslation: "The Prostration", versesCount: 30, revelationPlace: "makkah"),
        Surah(id: 33, nameArabic: "الأحزاب", nameSimple: "Al-Ahzab", nameTranslation: "The Combined Forces", versesCount: 73, revelationPlace: "madinah"),
        Surah(id: 34, nameArabic: "سبإ", nameSimple: "Saba", nameTranslation: "Sheba", versesCount: 54, revelationPlace: "makkah"),
        Surah(id: 35, nameArabic: "فاطر", nameSimple: "Fatir", nameTranslation: "Originator", versesCount: 45, revelationPlace: "makkah"),
        Surah(id: 36, nameArabic: "يس", nameSimple: "Ya-Sin", nameTranslation: "Ya Sin", versesCount: 83, revelationPlace: "makkah"),
        Surah(id: 37, nameArabic: "الصافات", nameSimple: "As-Saffat", nameTranslation: "Those who set the Ranks", versesCount: 182, revelationPlace: "makkah"),
        Surah(id: 38, nameArabic: "ص", nameSimple: "Sad", nameTranslation: "The Letter \"Saad\"", versesCount: 88, revelationPlace: "makkah"),
        Surah(id: 39, nameArabic: "الزمر", nameSimple: "Az-Zumar", nameTranslation: "The Troops", versesCount: 75, revelationPlace: "makkah"),
        Surah(id: 40, nameArabic: "غافر", nameSimple: "Ghafir", nameTranslation: "The Forgiver", versesCount: 85, revelationPlace: "makkah"),
        Surah(id: 41, nameArabic: "فصلت", nameSimple: "Fussilat", nameTranslation: "Explained in Detail", versesCount: 54, revelationPlace: "makkah"),
        Surah(id: 42, nameArabic: "الشورى", nameSimple: "Ash-Shuraa", nameTranslation: "The Consultation", versesCount: 53, revelationPlace: "makkah"),
        Surah(id: 43, nameArabic: "الزخرف", nameSimple: "Az-Zukhruf", nameTranslation: "The Ornaments of Gold", versesCount: 89, revelationPlace: "makkah"),
        Surah(id: 44, nameArabic: "الدخان", nameSimple: "Ad-Dukhan", nameTranslation: "The Smoke", versesCount: 59, revelationPlace: "makkah"),
        Surah(id: 45, nameArabic: "الجاثية", nameSimple: "Al-Jathiyah", nameTranslation: "The Crouching", versesCount: 37, revelationPlace: "makkah"),
        Surah(id: 46, nameArabic: "الأحقاف", nameSimple: "Al-Ahqaf", nameTranslation: "The Wind-Curved Sandhills", versesCount: 35, revelationPlace: "makkah"),
        Surah(id: 47, nameArabic: "محمد", nameSimple: "Muhammad", nameTranslation: "Muhammad", versesCount: 38, revelationPlace: "madinah"),
        Surah(id: 48, nameArabic: "الفتح", nameSimple: "Al-Fath", nameTranslation: "The Victory", versesCount: 29, revelationPlace: "madinah"),
        Surah(id: 49, nameArabic: "الحجرات", nameSimple: "Al-Hujurat", nameTranslation: "The Rooms", versesCount: 18, revelationPlace: "madinah"),
        Surah(id: 50, nameArabic: "ق", nameSimple: "Qaf", nameTranslation: "The Letter \"Qaf\"", versesCount: 45, revelationPlace: "makkah"),
        Surah(id: 51, nameArabic: "الذاريات", nameSimple: "Adh-Dhariyat", nameTranslation: "The Winnowing Winds", versesCount: 60, revelationPlace: "makkah"),
        Surah(id: 52, nameArabic: "الطور", nameSimple: "At-Tur", nameTranslation: "The Mount", versesCount: 49, revelationPlace: "makkah"),
        Surah(id: 53, nameArabic: "النجم", nameSimple: "An-Najm", nameTranslation: "The Star", versesCount: 62, revelationPlace: "makkah"),
        Surah(id: 54, nameArabic: "القمر", nameSimple: "Al-Qamar", nameTranslation: "The Moon", versesCount: 55, revelationPlace: "makkah"),
        Surah(id: 55, nameArabic: "الرحمن", nameSimple: "Ar-Rahman", nameTranslation: "The Beneficent", versesCount: 78, revelationPlace: "madinah"),
        Surah(id: 56, nameArabic: "الواقعة", nameSimple: "Al-Waqi'ah", nameTranslation: "The Inevitable", versesCount: 96, revelationPlace: "makkah"),
        Surah(id: 57, nameArabic: "الحديد", nameSimple: "Al-Hadid", nameTranslation: "The Iron", versesCount: 29, revelationPlace: "madinah"),
        Surah(id: 58, nameArabic: "المجادلة", nameSimple: "Al-Mujadila", nameTranslation: "The Pleading Woman", versesCount: 22, revelationPlace: "madinah"),
        Surah(id: 59, nameArabic: "الحشر", nameSimple: "Al-Hashr", nameTranslation: "The Exile", versesCount: 24, revelationPlace: "madinah"),
        Surah(id: 60, nameArabic: "الممتحنة", nameSimple: "Al-Mumtahanah", nameTranslation: "She that is to be examined", versesCount: 13, revelationPlace: "madinah"),
        Surah(id: 61, nameArabic: "الصف", nameSimple: "As-Saf", nameTranslation: "The Ranks", versesCount: 14, revelationPlace: "madinah"),
        Surah(id: 62, nameArabic: "الجمعة", nameSimple: "Al-Jumu'ah", nameTranslation: "The Congregation, Friday", versesCount: 11, revelationPlace: "madinah"),
        Surah(id: 63, nameArabic: "المنافقون", nameSimple: "Al-Munafiqun", nameTranslation: "The Hypocrites", versesCount: 11, revelationPlace: "madinah"),
        Surah(id: 64, nameArabic: "التغابن", nameSimple: "At-Taghabun", nameTranslation: "The Mutual Disillusion", versesCount: 18, revelationPlace: "madinah"),
        Surah(id: 65, nameArabic: "الطلاق", nameSimple: "At-Talaq", nameTranslation: "The Divorce", versesCount: 12, revelationPlace: "madinah"),
        Surah(id: 66, nameArabic: "التحريم", nameSimple: "At-Tahrim", nameTranslation: "The Prohibition", versesCount: 12, revelationPlace: "madinah"),
        Surah(id: 67, nameArabic: "الملك", nameSimple: "Al-Mulk", nameTranslation: "The Sovereignty", versesCount: 30, revelationPlace: "makkah"),
        Surah(id: 68, nameArabic: "القلم", nameSimple: "Al-Qalam", nameTranslation: "The Pen", versesCount: 52, revelationPlace: "makkah"),
        Surah(id: 69, nameArabic: "الحاقة", nameSimple: "Al-Haqqah", nameTranslation: "The Reality", versesCount: 52, revelationPlace: "makkah"),
        Surah(id: 70, nameArabic: "المعارج", nameSimple: "Al-Ma'arij", nameTranslation: "The Ascending Stairways", versesCount: 44, revelationPlace: "makkah"),
        Surah(id: 71, nameArabic: "نوح", nameSimple: "Nuh", nameTranslation: "Noah", versesCount: 28, revelationPlace: "makkah"),
        Surah(id: 72, nameArabic: "الجن", nameSimple: "Al-Jinn", nameTranslation: "The Jinn", versesCount: 28, revelationPlace: "makkah"),
        Surah(id: 73, nameArabic: "المزمل", nameSimple: "Al-Muzzammil", nameTranslation: "The Enshrouded One", versesCount: 20, revelationPlace: "makkah"),
        Surah(id: 74, nameArabic: "المدثر", nameSimple: "Al-Muddaththir", nameTranslation: "The Cloaked One", versesCount: 56, revelationPlace: "makkah"),
        Surah(id: 75, nameArabic: "القيامة", nameSimple: "Al-Qiyamah", nameTranslation: "The Resurrection", versesCount: 40, revelationPlace: "makkah"),
        Surah(id: 76, nameArabic: "الانسان", nameSimple: "Al-Insan", nameTranslation: "The Man", versesCount: 31, revelationPlace: "madinah"),
        Surah(id: 77, nameArabic: "المرسلات", nameSimple: "Al-Mursalat", nameTranslation: "The Emissaries", versesCount: 50, revelationPlace: "makkah"),
        Surah(id: 78, nameArabic: "النبإ", nameSimple: "An-Naba", nameTranslation: "The Tidings", versesCount: 40, revelationPlace: "makkah"),
        Surah(id: 79, nameArabic: "النازعات", nameSimple: "An-Nazi'at", nameTranslation: "Those who drag forth", versesCount: 46, revelationPlace: "makkah"),
        Surah(id: 80, nameArabic: "عبس", nameSimple: "'Abasa", nameTranslation: "He Frowned", versesCount: 42, revelationPlace: "makkah"),
        Surah(id: 81, nameArabic: "التكوير", nameSimple: "At-Takwir", nameTranslation: "The Overthrowing", versesCount: 29, revelationPlace: "makkah"),
        Surah(id: 82, nameArabic: "الإنفطار", nameSimple: "Al-Infitar", nameTranslation: "The Cleaving", versesCount: 19, revelationPlace: "makkah"),
        Surah(id: 83, nameArabic: "المطففين", nameSimple: "Al-Mutaffifin", nameTranslation: "The Defrauding", versesCount: 36, revelationPlace: "makkah"),
        Surah(id: 84, nameArabic: "الإنشقاق", nameSimple: "Al-Inshiqaq", nameTranslation: "The Sundering", versesCount: 25, revelationPlace: "makkah"),
        Surah(id: 85, nameArabic: "البروج", nameSimple: "Al-Buruj", nameTranslation: "The Mansions of the Stars", versesCount: 22, revelationPlace: "makkah"),
        Surah(id: 86, nameArabic: "الطارق", nameSimple: "At-Tariq", nameTranslation: "The Nightcommer", versesCount: 17, revelationPlace: "makkah"),
        Surah(id: 87, nameArabic: "الأعلى", nameSimple: "Al-A'la", nameTranslation: "The Most High", versesCount: 19, revelationPlace: "makkah"),
        Surah(id: 88, nameArabic: "الغاشية", nameSimple: "Al-Ghashiyah", nameTranslation: "The Overwhelming", versesCount: 26, revelationPlace: "makkah"),
        Surah(id: 89, nameArabic: "الفجر", nameSimple: "Al-Fajr", nameTranslation: "The Dawn", versesCount: 30, revelationPlace: "makkah"),
        Surah(id: 90, nameArabic: "البلد", nameSimple: "Al-Balad", nameTranslation: "The City", versesCount: 20, revelationPlace: "makkah"),
        Surah(id: 91, nameArabic: "الشمس", nameSimple: "Ash-Shams", nameTranslation: "The Sun", versesCount: 15, revelationPlace: "makkah"),
        Surah(id: 92, nameArabic: "الليل", nameSimple: "Al-Layl", nameTranslation: "The Night", versesCount: 21, revelationPlace: "makkah"),
        Surah(id: 93, nameArabic: "الضحى", nameSimple: "Ad-Duhaa", nameTranslation: "The Morning Hours", versesCount: 11, revelationPlace: "makkah"),
        Surah(id: 94, nameArabic: "الشرح", nameSimple: "Ash-Sharh", nameTranslation: "The Relief", versesCount: 8, revelationPlace: "makkah"),
        Surah(id: 95, nameArabic: "التين", nameSimple: "At-Tin", nameTranslation: "The Fig", versesCount: 8, revelationPlace: "makkah"),
        Surah(id: 96, nameArabic: "العلق", nameSimple: "Al-'Alaq", nameTranslation: "The Clot", versesCount: 19, revelationPlace: "makkah"),
        Surah(id: 97, nameArabic: "القدر", nameSimple: "Al-Qadr", nameTranslation: "The Power", versesCount: 5, revelationPlace: "makkah"),
        Surah(id: 98, nameArabic: "البينة", nameSimple: "Al-Bayyinah", nameTranslation: "The Clear Proof", versesCount: 8, revelationPlace: "madinah"),
        Surah(id: 99, nameArabic: "الزلزلة", nameSimple: "Az-Zalzalah", nameTranslation: "The Earthquake", versesCount: 8, revelationPlace: "madinah"),
        Surah(id: 100, nameArabic: "العاديات", nameSimple: "Al-'Adiyat", nameTranslation: "The Courser", versesCount: 11, revelationPlace: "makkah"),
        Surah(id: 101, nameArabic: "القارعة", nameSimple: "Al-Qari'ah", nameTranslation: "The Calamity", versesCount: 11, revelationPlace: "makkah"),
        Surah(id: 102, nameArabic: "التكاثر", nameSimple: "At-Takathur", nameTranslation: "The Rivalry in world increase", versesCount: 8, revelationPlace: "makkah"),
        Surah(id: 103, nameArabic: "العصر", nameSimple: "Al-'Asr", nameTranslation: "The Declining Day", versesCount: 3, revelationPlace: "makkah"),
        Surah(id: 104, nameArabic: "الهمزة", nameSimple: "Al-Humazah", nameTranslation: "The Traducer", versesCount: 9, revelationPlace: "makkah"),
        Surah(id: 105, nameArabic: "الفيل", nameSimple: "Al-Fil", nameTranslation: "The Elephant", versesCount: 5, revelationPlace: "makkah"),
        Surah(id: 106, nameArabic: "قريش", nameSimple: "Quraysh", nameTranslation: "Quraysh", versesCount: 4, revelationPlace: "makkah"),
        Surah(id: 107, nameArabic: "الماعون", nameSimple: "Al-Ma'un", nameTranslation: "The Small kindnesses", versesCount: 7, revelationPlace: "makkah"),
        Surah(id: 108, nameArabic: "الكوثر", nameSimple: "Al-Kawthar", nameTranslation: "The Abundance", versesCount: 3, revelationPlace: "makkah"),
        Surah(id: 109, nameArabic: "الكافرون", nameSimple: "Al-Kafirun", nameTranslation: "The Disbelievers", versesCount: 6, revelationPlace: "makkah"),
        Surah(id: 110, nameArabic: "النصر", nameSimple: "An-Nasr", nameTranslation: "The Divine Support", versesCount: 3, revelationPlace: "madinah"),
        Surah(id: 111, nameArabic: "المسد", nameSimple: "Al-Masad", nameTranslation: "The Palm Fiber", versesCount: 5, revelationPlace: "makkah"),
        Surah(id: 112, nameArabic: "الإخلاص", nameSimple: "Al-Ikhlas", nameTranslation: "The Sincerity", versesCount: 4, revelationPlace: "makkah"),
        Surah(id: 113, nameArabic: "الفلق", nameSimple: "Al-Falaq", nameTranslation: "The Daybreak", versesCount: 5, revelationPlace: "makkah"),
        Surah(id: 114, nameArabic: "الناس", nameSimple: "An-Nas", nameTranslation: "Mankind", versesCount: 6, revelationPlace: "makkah"),
    ]
}
